# Generated by Django 4.2.5 on 2023-10-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
