# Generated by Django 4.2.5 on 2023-10-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0003_studyspace_approved_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='user_email',
            field=models.CharField(default='rqf8pe@virginia.edu', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyspace',
            name='approved_submission',
            field=models.IntegerField(choices=[(1, 'Approved'), (0, 'Pending'), (-1, 'Denied')], default=0),
        ),
    ]
