# Generated by Django 4.2.6 on 2023-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0004_studyspace_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='denial_reason',
            field=models.CharField(default='', max_length=200),
        ),
    ]
