# Generated by Django 4.2.6 on 2023-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0006_studyspace_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='has_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='has_outlets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='has_printers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='has_whiteboards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='is_outside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='is_quiet',
            field=models.BooleanField(default=False),
        ),
    ]
