# Generated by Django 4.2.6 on 2023-12-01 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0007_studyspace_has_food_studyspace_has_outlets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
