# Generated by Django 4.2.7 on 2023-12-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0008_studyspace_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyspace',
            old_name='information',
            new_name='other_information',
        ),
    ]
