# Generated by Django 4.2.7 on 2023-12-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces', '0009_rename_information_studyspace_other_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='environment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='hours',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='traffic',
            field=models.TextField(default=''),
        ),
    ]
